---
title: "Homework 1"
author: 
  - Makayla Whitney
  - Joe Swinehart
  - Janette Avelar
  - David Fainstein
date: "2/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
#library(dplyr) # you shouldn't need to load dplyr, because it's loaded with the tidyverse
library(gghighlight)
```

```{r Read in Data}
#here::here("data")

assessments <- read_csv(here("data", "assessments.csv"))
courses     <- read_csv(here("data", "courses.csv"))
stu_assess  <- read_csv(here("data", "studentAssessment.csv"))
stu_info    <- read_csv(here("data", "studentInfo.csv"))
stu_reg     <- read_csv(here("data", "studentRegistration.csv"))
stu_vle     <- read_csv(here("data", "studentVle.csv"))
vle         <- read_csv(here("data", "vle.csv"))
```


```{r Mutating Join 1}
MJ1 <- left_join(stu_info, stu_assess) %>% 
  select(id_student,
         final_result,
         highest_education,
         gender,
         score) %>% 
  mutate(score = as.numeric(score)) %>% 
  group_by(highest_education, gender, final_result) %>% 
  summarise(score = mean(score, na.rm = TRUE)) %>% 
  mutate(highest_education = as.factor(highest_education)) %>% 
  mutate(highest_education = fct_relevel(highest_education,
             "No Formal quals",
             "Lower Than A Level",
             "A Level or Equivalent",
             "HE Qualification",
             "Post Graduate Qualification"))

# Unfortunately the above is an error. We can confirm this with the following
# stu_info %>% 
#   count(id_student) %>% 
#   filter(n > 1)
# 
# stu_assess %>% 
#   count(id_student) %>% 
#   filter(n > 1)
# 
# Both of the above return rows, which means if you join the datasets by 
# `id_student` you're in a many-to-many join situation.
#
# I've removed two points from the above.
```

```{r Data Display 1}

ggplot(MJ1, aes(score, highest_education)) +
  geom_line() +
  geom_point(aes(color = gender)) +
  facet_wrap(~final_result) +
  labs(x = "Average Score",
       y = "Highest Education ") +
  scale_color_manual(values = c("#66B2FF", "#0066CC"))

# I made a few suggested edits to the above. I tend to put groupings on the
# specific layer, rather than at the top layer where it will bleed through to
# all of the others. I also like adding the line between the points.
```

```{r Mutating Join 2}
MJ2 <- left_join(stu_vle, vle) %>% 
  select(code_module,
         code_presentation,
         id_student,
         sum_click,
         activity_type) %>% 
  mutate(activity_type = factor(activity_type,
                                levels = c("oucontent",
                                           "forumng",
                                           "quiz",
                                           "homepage",
                                           "subpage",
                                           "resource",
                                           "ouwiki",
                                           "url",
                                           "oucollaborate",
                                           "glossary",
                                           "questionnaire",
                                           "externalquiz",
                                           "page",
                                           "dataplus",
                                           "ouelluminate",
                                           "dualpane",
                                           "htmlactivity",
                                           "folder",
                                           "sharedsubpage",
                                           "repeatactivity"))) %>% 
  group_by(id_student, activity_type, code_presentation, code_module) %>% 
  summarize(sum_click = mean(sum_click))

# Nice join!

#Labels for facetting courses
course_lab <- c("AAA" = "Course A", 
            "BBB" = "Course B", 
            "CCC" = "Course C",
            "DDD" = "Course D",
            "EEE" = "Course E",
            "FFF" = "Course F",
            "GGG" = "Course G")

#Data to figure out labels for annotating - shows average daily clicks
mean_click <- MJ2 %>% 
  group_by(activity_type, code_module) %>% 
  summarize(total_sum = round(mean(sum_click), digits = 1)) %>% 
  filter(code_module == "AAA" & activity_type == "oucontent" |
         code_module == "BBB" & activity_type == "oucontent"  |
         code_module == "CCC" & activity_type == "quiz" |
         code_module == "DDD" & activity_type == "glossary" |
         code_module == "EEE" & activity_type == "quiz" |
         code_module == "FFF" & activity_type == "quiz" |
         code_module == "GGG" & activity_type == "oucontent") 

# Labels for annotating across facets... hope it works!
f_labels <- data.frame(code_module = factor(
                               c("AAA",
                                 "BBB",
                                 "CCC",
                                 "DDD",
                                 "EEE",
                                 "FFF",
                                 "GGG")),
                       label = c(4.44,
                                 3.88,
                                 5.11,
                                 7.23,
                                 8.15,
                                 9.36,
                                 5.85))
# It didn't work :(
# I've spent too much time trying to get this figured out so I'm moving on.
# Feel free to tinker with labels--the goal was to label the highlighted
# group within each facet (course) with average number of clicks.

# I'm not exactly sure what you were after here but I'd be happy to walk through
# it with you if you'd like to schedule a time to meet
```

```{r Data Display 2}
ggplot(subset(MJ2, activity_type %in% c("oucontent",
                                        "forumng",
                                        "quiz",
                                        "homepage",
                                        "glossary")),
              aes(activity_type, sum_click)) +
  geom_point(color = "#b69c91",
             alpha = .4,
             position = position_jitter(width = .2,
                                        height = .5,
                                        seed = 23)) +
  geom_point(color = "#f7af00",
             alpha = .4,
             show.legend = FALSE,
             position = position_jitter(width = .2,
                                        height = .5,
                                        seed = 23),
             data = filter(MJ2,
                          code_module == "AAA" & activity_type == "oucontent" |
                          code_module == "BBB" & activity_type == "oucontent" |
                          code_module == "CCC" & activity_type == "quiz" |
                          code_module == "DDD" & activity_type == "glossary" |
                          code_module == "EEE" & activity_type == "quiz" |
                          code_module == "FFF" & activity_type == "quiz" |
                          code_module == "GGG" & activity_type == "oucontent")) +
  facet_grid(cols = vars(code_module),
             labeller = labeller(code_module = course_lab)) +
  geom_text(data = mean_click, aes(x = activity_type, y = 10, label = total_sum)) +
  coord_flip() +
  theme_light() +
  theme(plot.title = element_text(face = "bold",
                                  hjust = 0.5),
        axis.text.x = element_blank()) +
  scale_x_discrete(labels = c("oucontent" = "Course Content",
                              "forumng" = "Forum",
                              "quiz" = "Quiz",
                              "homepage" = "Home Page",
                              "glossary" = "Glossary")) +
  labs(title = "Top Online Content Interaction 2013-2014",
       caption = "Plot limited to show most interacted with content areas.",
       y = "Daily Clicks by Enrolled Students",
       x = "")

# It looks like maybe you did get it to work?
# oh... but maybe the jitter is still messed up? I wonder if you could have
# created a variable in your dataset for the points you wanted to highlight,
# then just use `aes(color = highlight_column)`?
```

```{r Mutating Join 3}
reg_stu_info <- stu_reg %>% 
  left_join(stu_info, 
            by =c ("code_module", "code_presentation", "id_student")) 

# Nice join!
```
## I am not sure if this really answers my question as clearly as I expected it to. I guess I can tell that students who passed with distinction were very unlikely to register late for the course, anyhow. Also I guess I noticed that the eventually "Withdrawn" students didn't have as pronounced of a widening about a month before the course started. Interesting.
```{r Data Display 3}
ggplot(reg_stu_info, aes(x = final_result, y = date_registration )) +
  geom_violin(scale = "area", fill = "cornflowerblue") +
  scale_x_discrete(limits = c("Withdrawn", "Fail", "Pass", "Distinction")) +
  labs(title = 'Do Earlier Prepared Students Fare Better?', 
       subtitle = 'Registration Dates vs Final Outcomes', 
       y = 'Relative Registration Date',
       x = 'Final Score') + 
  theme(plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic'))
  
  #  geom_dotplot(binaxis = "y", stackdir = "center", dotsize =.01) 


```

```{r Filtering Join}
stu_assess_avg <- stu_assess %>%
  mutate(score = as.numeric(score)) %>% 
  group_by(id_student) %>%
  summarize(score_avg = mean(score) + 3*sd(score),
            score_avg = unique(score_avg))

cut_mean <- stu_assess_avg %>%
  ungroup() %>%
  filter(stu_assess_avg > score_avg)

semi_join(stu_assess, cut_mean)
  
# 👍
```

```{r Reproduced Figure}

ggplot(MJ1, aes(score, highest_education, color = gender)) +
  geom_line(color = "#636363", size = 2) +
  geom_point(size = 3) +
  facet_wrap(~final_result) +
  labs(x = "Average Score",
       y = "Highest Education ") +
  scale_color_manual(values = c("#66B2FF", "#0066CC")) +
  theme_minimal()

# Nice job. I would have liked to have seen `ncol = 1` passed to `facet_wrap()`
# but generally this looks good.
```

```{r Extra Credit (Optional)}

#work in progress - just playing with adding a column to match the color with 

higher_mean <- MJ1 %>%
  mutate(higher_mean = mean(score)) %>%
  summarize(higher_mean = unique(higher_mean))

ggplot(MJ1, aes(score, highest_education, color = gender)) +
  geom_line(aes(higher_mean, color = "#636363", size = 2)) +
  geom_point(size = 3) +
  facet_wrap(~final_result) +
  labs(x = "Average Score",
       y = "Highest Education ") +
  scale_color_manual(values = c("#66B2FF", "#0066CC")) +
  theme_minimal()

# I got an error here
```
